version: "3.9"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.21
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 20s
      retries: 10
      start_period: 30s
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
  
  tsakorpus:
    container_name: tsakorpus
    build:
      context: ./tsakorpus
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      elasticsearch:
        condition: service_healthy

  nginx:
    container_name: nginx
    image: nginx:1.26
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - ${NGINX_PORT}:80
    depends_on:
      - tsakorpus
